//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorenMarquardtAdminModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftrag
    {
        public int ID { get; set; }
        public string Kunde { get; set; }
        public string Auftragsnummer { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<System.TimeSpan> GeplanteZeit { get; set; }
        public Nullable<bool> Beendet { get; set; }
    }
}
