//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorenMarquardtAdminModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zeiten
    {
        public int ID { get; set; }
        public Nullable<int> AuftragID { get; set; }
        public string Mitarbeiter { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<bool> Beendet { get; set; }
        public bool Nachgetragen { get; set; }
    }
}
